apiVersion: apps/v1
kind: Deployment
metadata:
  name: order_service
  namespace: test
spec:
  strategy:
    type: rollingUpdate
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  minReadySeconds: 30
  replicas: 3
  selector:
    matchLabels:
      app: order
  template:
    metadata:
      labels:
        app: order
    spec:
      containers:
      - name: order_service
        image:  shahirsyed5890/order_service:v1.0.version
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 256m
            memory: 256Mi
          limits:
            cpu: 512m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 30
          timeoutSeconds: 30